# Difference method

In this model, we will calculate the difference between the experimental band gap and the PBE band gap.

In [1]:
from modnet.preprocessing import MODData
from modnet.models import MODNetModel
import numpy as np
import pandas as pd
import os
import copy
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

In [2]:
from sklearn.model_selection import KFold
from modnet.preprocessing import MODData

def shuffle_MD(data,random_state=10):
    data = copy.deepcopy(data)
    ids = data.df_targets.sample(frac=1,random_state=random_state).index
    data.df_featurized = data.df_featurized.loc[ids]
    data.df_targets = data.df_targets.loc[ids]
    data.df_structure = data.df_structure.loc[ids]
    
    return data

def MDKsplit(data,n_splits=5,random_state=10):
    data = shuffle_MD(data,random_state=random_state)
    ids = np.array(data.structure_ids)
    kf = KFold(n_splits=n_splits,shuffle=True,random_state=random_state)
    folds = []
    for train_idx, val_idx in kf.split(ids):
        data_train = MODData(data.df_structure.iloc[train_idx]['structure'].values,data.df_targets.iloc[train_idx].values,target_names=data.df_targets.columns,structure_ids=ids[train_idx])
        data_train.df_featurized = data.df_featurized.iloc[train_idx]
        #data_train.optimal_features = data.optimal_features
        
        data_val = MODData(data.df_structure.iloc[val_idx]['structure'].values,data.df_targets.iloc[val_idx].values,target_names=data.df_targets.columns,structure_ids=ids[val_idx])
        data_val.df_featurized = data.df_featurized.iloc[val_idx]
        #data_val.optimal_features = data.optimal_features

        folds.append((data_train,data_val))
        
    return folds

def MD_append(md,lmd):
    md = copy.deepcopy(md)
    for m in lmd:
        md.df_structure.append(m.df_structure)
        md.df_targets.append(m.df_targets)
        md.df_featurized.append(m.df_featurized)
    return md

In [3]:
md_exp = MODData.load('exp_gap_all_mpid')
md_exp.df_targets.columns = ['exp_gap','mp_id']
md_pbe = MODData.load('pbe_gap.zip')
md_pbe.df_targets.columns = ['gap']
md_joint = MODData.load('exp_pbe_joint')


If you use the ChemEnv tool for your research, please consider citing the following reference(s) :
David Waroquiers, Xavier Gonze, Gian-Marco Rignanese, Cathrin Welker-Nieuwoudt, Frank Rosowski,
Michael Goebel, Stephan Schenk, Peter Degelmann, Rute Andre, Robert Glaum, and Geoffroy Hautier,
"Statistical analysis of coordination environments in oxides",
Chem. Mater., 2017, 29 (19), pp 8346-8360,
DOI: 10.1021/acs.chemmater.7b02766



INFO:root:Loaded <modnet.preprocessing.MODData object at 0x7f6a9d2ea820> object, created with modnet version <=0.1.7
INFO:root:Loaded <modnet.preprocessing.MODData object at 0x7f6a9d2ea970> object, created with modnet version <=0.1.7
INFO:root:Loaded <modnet.preprocessing.MODData object at 0x7f6a9e34faf0> object, created with modnet version <=0.1.7


In [ ]:
#df_pbe = pd.read_pickle("df_pbe.pkl")

In [4]:
from megnet.models import MEGNetModel

#Pretrained model (we are using transfer learning)

model_form = MEGNetModel.from_file('band_gap_regression.hdf5')

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [5]:
md_joint.df_targets

exp_gap  pbe_gap
mp-12699      0.00   0.0000
mp-559459     3.40   2.1704
mp-21162      0.00   0.0000
mp-1306       0.00   0.0000
mp-15252      0.53   0.1049
...            ...      ...
mp-556541     1.80   1.5135
mp-2602       1.04   0.0000
mp-30366      0.00   0.0000
mp-3718       1.45   0.2418
mp-3709       0.00   0.0000

[1703 rows x 2 columns]

In [24]:
md_joint.df_targets['structure'] = df_pbe['structure']

In [25]:
md_joint.df_targets

exp_gap  pbe_gap                                          structure
mp-12699      0.00   0.0000  [[ 0.13616363 -2.60631371  1.50340165] Ca, [-1...
mp-559459     3.40   2.1704  [[2.14049282 6.43464803 1.76199846] Cs, [-0.70...
mp-21162      0.00   0.0000  [[0. 0. 0.] Sr, [0.        2.5259875 2.5259875...
mp-1306       0.00   0.0000  [[3.259129   1.88166243 1.15971025] Th, [ 3.25...
mp-15252      0.53   0.1049  [[0.95531657 1.042239   0.86229681] Cu, [2.803...
...            ...      ...                                                ...
mp-556541     1.80   1.5135  [[-2.16130472e-17  6.49363948e+00  5.82657217e...
mp-2602       1.04   0.0000   [[3.023318 3.023318 3.023318] Nd, [0. 0. 0.] As]
mp-30366      0.00   0.0000  [[4.51774558 1.37529211 4.32659015] Ca, [1.109...
mp-3718       1.45   0.2418  [[2.0697935  0.         1.28932533] Th, [0.   ...
mp-3709       0.00   0.0000  [[0. 0. 0.] Tb, [0.       1.983905 2.537711] C...

[1703 rows x 3 columns]

In [29]:
from pymatgen.ext.matproj import MPRester

with MPRester(api_key='v454AlrxL5Zg0cLAXW0') as mpr:
    for i in range(len(md_joint.df_targets)):
        md_joint.df_targets['structure'][i] = mpr.get_structure_by_material_id(md_joint.df_targets.index[i])

In [30]:
pred = [model_form.predict_structure(x) for x in md_joint.df_targets['structure']]

In [31]:
pred

[array([0.08305275], dtype=float32),
 array([2.1316535], dtype=float32),
 array([0.11622305], dtype=float32),
 array([0.09763134], dtype=float32),
 array([0.14685974], dtype=float32),
 array([0.67693174], dtype=float32),
 array([0.04112521], dtype=float32),
 array([0.41912085], dtype=float32),
 array([1.5994573], dtype=float32),
 array([5.2658362], dtype=float32),
 array([1.6570518], dtype=float32),
 array([1.8150771], dtype=float32),
 array([0.9078939], dtype=float32),
 array([0.5344136], dtype=float32),
 array([0.03136301], dtype=float32),
 array([0.04260066], dtype=float32),
 array([5.258303], dtype=float32),
 array([0.0767439], dtype=float32),
 array([4.4145827], dtype=float32),
 array([0.05073041], dtype=float32),
 array([1.3067894], dtype=float32),
 array([3.1201158], dtype=float32),
 array([0.01684257], dtype=float32),
 array([0.0610365], dtype=float32),
 array([0.98575485], dtype=float32),
 array([0.11413923], dtype=float32),
 array([2.188607], dtype=float32),
 array([0.0264222

In [32]:
pred = pd.Series(list(map(float, pred)))

In [33]:
pred

0       0.083053
1       2.131654
2       0.116223
3       0.097631
4       0.146860
          ...   
1698    1.568193
1699    0.087049
1700    0.221409
1701    0.314326
1702    0.025343
Length: 1703, dtype: float64

In [38]:
md_joint.df_targets['gap megnet'] = np.nan

In [39]:
for i in range(len(pred)):
    md_joint.df_targets['gap megnet'][i] = pred[i]

In [45]:
md_joint.df_targets = md_joint.df_targets.drop(columns=['structure', 'pbe_gap'])

In [46]:
md_joint.df_targets

exp_gap  gap megnet
mp-12699      0.00    0.083053
mp-559459     3.40    2.131654
mp-21162      0.00    0.116223
mp-1306       0.00    0.097631
mp-15252      0.53    0.146860
...            ...         ...
mp-556541     1.80    1.568193
mp-2602       1.04    0.087049
mp-30366      0.00    0.221409
mp-3718       1.45    0.314326
mp-3709       0.00    0.025343

[1703 rows x 2 columns]

In [47]:
md_joint.df_targets['difference'] = md_joint.df_targets['exp_gap'] - md_joint.df_targets['gap megnet']

In [48]:
md_joint.df_targets

exp_gap  gap megnet  difference
mp-12699      0.00    0.083053   -0.083053
mp-559459     3.40    2.131654    1.268346
mp-21162      0.00    0.116223   -0.116223
mp-1306       0.00    0.097631   -0.097631
mp-15252      0.53    0.146860    0.383140
...            ...         ...         ...
mp-556541     1.80    1.568193    0.231807
mp-2602       1.04    0.087049    0.952951
mp-30366      0.00    0.221409   -0.221409
mp-3718       1.45    0.314326    1.135674
mp-3709       0.00    0.025343   -0.025343

[1703 rows x 3 columns]

In [49]:
k = 5
random_state = 202010
folds = MDKsplit(md_joint,n_splits=k,random_state=random_state)
maes = np.ones(5)
for i,f in enumerate(folds):
    train = f[0]
    test = f[1]
    train.feature_selection(n=-1, use_precomputed_cross_nmi=True)
    '''fpath = 'trainA_{}_{}'.format(random_state,i+1)
    if os.path.exists(fpath):
        train = MODData.load(fpath)
    else:
        train.feature_selection(n=-1, use_precomputed_cross_nmi=True)
        train.save(fpath)
    '''   
    # assure no overlap
    #assert len(set(train.df_targets.index).intersection(set(test.df_targets.index))) == 0
    
    # difference prediction
    model = MODNetModel([[['difference']]],{'difference':1})
    model.fit_preset(train,verbose=0)
    
    pred = model.predict(test)
    true = test.df_targets
    true = true.drop(columns=['exp_gap','gap megnet'])
    error = pred-true
    error = error['difference'].drop(pred.index[((pred['difference']).abs()>20)]) # drop unrealistic values: happens extremely rarely
    mae = np.abs(error).mean()
    print('mae')
    print(mae)
    maes[i] = mae
    

INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loaded DeBreuck2020Featurizer featurizer.
INFO:root:Loading cross NMI from 'Features_cross' file.
INFO:root:Starting target 1/3: exp_gap ...
INFO:root:Computing mutual information between features and target...
INFO:root:Computing optimal features...
INFO:root:Selected 50/1102 features...
INFO:root:Selected 100/1102 features...
INFO:root:Selected 150/1102 features...
INFO:root:Selected 200/1102 features...
INFO:root:Selected 250/1102 features...
INFO:root:Selected 300/1102 features...
INFO:root:Selected 350/1102 feat

mae
0.4507365792158779


INFO:root:Computing optimal features...
INFO:root:Selected 50/1095 features...
INFO:root:Selected 100/1095 features...
INFO:root:Selected 150/1095 features...
INFO:root:Selected 200/1095 features...
INFO:root:Selected 250/1095 features...
INFO:root:Selected 300/1095 features...
INFO:root:Selected 350/1095 features...
INFO:root:Selected 400/1095 features...
INFO:root:Selected 450/1095 features...
INFO:root:Selected 500/1095 features...
INFO:root:Selected 550/1095 features...
INFO:root:Selected 600/1095 features...
INFO:root:Selected 650/1095 features...
INFO:root:Selected 700/1095 features...
INFO:root:Selected 750/1095 features...
INFO:root:Selected 800/1095 features...
INFO:root:Selected 850/1095 features...
INFO:root:Selected 900/1095 features...
INFO:root:Selected 950/1095 features...
INFO:root:Selected 1000/1095 features...
INFO:root:Selected 1050/1095 features...
INFO:root:Done with target 1/3: exp_gap.
INFO:root:Starting target 2/3: gap megnet ...
INFO:root:Computing mutual infor

mae
0.3902799221486737


INFO:root:Starting target 1/3: exp_gap ...
INFO:root:Computing mutual information between features and target...
INFO:root:Computing optimal features...
INFO:root:Selected 50/1104 features...
INFO:root:Selected 100/1104 features...
INFO:root:Selected 150/1104 features...
INFO:root:Selected 200/1104 features...
INFO:root:Selected 250/1104 features...
INFO:root:Selected 300/1104 features...
INFO:root:Selected 350/1104 features...
INFO:root:Selected 400/1104 features...
INFO:root:Selected 450/1104 features...
INFO:root:Selected 500/1104 features...
INFO:root:Selected 550/1104 features...
INFO:root:Selected 600/1104 features...
INFO:root:Selected 650/1104 features...
INFO:root:Selected 700/1104 features...
INFO:root:Selected 750/1104 features...
INFO:root:Selected 800/1104 features...
INFO:root:Selected 850/1104 features...
INFO:root:Selected 900/1104 features...
INFO:root:Selected 950/1104 features...
INFO:root:Selected 1000/1104 features...
INFO:root:Selected 1050/1104 features...
INFO:r

mae
0.3717351020663566


INFO:root:Computing optimal features...
INFO:root:Selected 50/1099 features...
INFO:root:Selected 100/1099 features...
INFO:root:Selected 150/1099 features...
INFO:root:Selected 200/1099 features...
INFO:root:Selected 250/1099 features...
INFO:root:Selected 300/1099 features...
INFO:root:Selected 350/1099 features...
INFO:root:Selected 400/1099 features...
INFO:root:Selected 450/1099 features...
INFO:root:Selected 500/1099 features...
INFO:root:Selected 550/1099 features...
INFO:root:Selected 600/1099 features...
INFO:root:Selected 650/1099 features...
INFO:root:Selected 700/1099 features...
INFO:root:Selected 750/1099 features...
INFO:root:Selected 800/1099 features...
INFO:root:Selected 850/1099 features...
INFO:root:Selected 900/1099 features...
INFO:root:Selected 950/1099 features...
INFO:root:Selected 1000/1099 features...
INFO:root:Selected 1050/1099 features...
INFO:root:Done with target 1/3: exp_gap.
INFO:root:Starting target 2/3: gap megnet ...
INFO:root:Computing mutual infor

mae
0.37562334156145516


INFO:root:Computing optimal features...
INFO:root:Selected 50/1094 features...
INFO:root:Selected 100/1094 features...
INFO:root:Selected 150/1094 features...
INFO:root:Selected 200/1094 features...
INFO:root:Selected 250/1094 features...
INFO:root:Selected 300/1094 features...
INFO:root:Selected 350/1094 features...
INFO:root:Selected 400/1094 features...
INFO:root:Selected 450/1094 features...
INFO:root:Selected 500/1094 features...
INFO:root:Selected 550/1094 features...
INFO:root:Selected 600/1094 features...
INFO:root:Selected 650/1094 features...
INFO:root:Selected 700/1094 features...
INFO:root:Selected 750/1094 features...
INFO:root:Selected 800/1094 features...
INFO:root:Selected 850/1094 features...
INFO:root:Selected 900/1094 features...
INFO:root:Selected 950/1094 features...
INFO:root:Selected 1000/1094 features...
INFO:root:Selected 1050/1094 features...
INFO:root:Done with target 1/3: exp_gap.
INFO:root:Starting target 2/3: gap megnet ...
INFO:root:Computing mutual infor

mae
0.42660957318041076


In [50]:
maes

array([0.45073658, 0.39027992, 0.3717351 , 0.37562334, 0.42660957])

In [51]:
maes.mean()

0.4029969036345548

#### Conclusion

No significant improvement.